### ISSUE TITLE
Can you make a demo or all in one how to use your package?

### ISSUE THREAD

**Issue by stojankukrika** [techancubate/Angular-Agora-RTC-ANC#4]
Hi,
Can you make a demo or all-in-one on how to use your package? It will help me a lot to know better this package and use it in my demo school project.

**Comment by turivishal** [comment]
This is a clone of [angular-agora-rtc npm](https://www.npmjs.com/package/angular-agora-rtc),
They are not updating the NPM for 4 years and there are versions dependencies of latest `agora-rtc-sdk` version and support of the latest `angular/common`, so we have just updated those versions in `package.json` file and using this NPM.

You will find the docs in agora docs,
https://www.agora.io/en/developer-resources/
https://docs.agora.io/en

**Comment by techancdev** [comment]
This is a clone of [angular-agora-rtc npm](https://www.npmjs.com/package/angular-agora-rtc),
They are not updating the NPM for 4 years and there are versions dependencies of latest `agora-rtc-sdk` version and support of the latest `angular/common`, so we have just updated those versions in `package.json` file and using this NPM.

You will find the docs in agora docs,
https://www.agora.io/en/developer-resources/
https://docs.agora.io/en

**Comment by stojankukrika** [comment]
thank you for this package! I see that the original package didn't work for some reason and I didn't find out why. Hope that this package will work.
Can you update angular/core and angular/common into newer version 14?
